### ISSUE TITLE
pushers may fill up disk

### ISSUE THREAD

**Issue by munkyboy** [obsrvbl/ona#7]
```gherkin
Given ONA is unable to upload files to obsrvbl
And a file producer continues to output files
Then ONA will fill up the temp partition with archives
```

I have not tested this. It is based on my reading of [pusher.py](https://github.com/obsrvbl/ona/blob/master/src/scripts/ona_service/pusher.py#L181-L184)

It seems like the contract is: file producers create files and ONA will take of getting them uploaded. Since the original files are deleted by ONA, I assume the contract includes ONA performing cleanup of it's own archive representations.

Apologizes in advance if I misread what the code is doing.

**Comment by bbayles** [comment]
Please use the obsrvbl/devops repo for these issues. Thanks!
